pipeline:
  name: Wasi
  identifier: Wasi
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Layer
        identifier: Layer
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      FROM vm/ubuntu:18.04

                      # install docker-ce (from tutorial for ubuntu)
                      RUN apt-get update && \
                          apt-get install apt-transport-https ca-certificates curl software-properties-common && \
                          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
                          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && \
                          apt-get update && \
                          apt install docker-ce

                      # install docker compose
                      RUN curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
                          chmod +x /usr/local/bin/docker-compose

                      # copy the root (i.e., repository root) to /root in the runner
                      COPY / /root

                      RUN REPEATABLE docker-compose up -d --build --force-recreate --remove-orphans && sleep 6

                      EXPOSE WEBSITE localhost:8000
                  description: Parameter
  properties:
    ci:
      codebase:
        connectorRef: Wasi_Test
        repoName: Ci-CD-Practice
        build: <+input>
