pipeline:
  name: Wasi
  identifier: Wasi
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      # Navigate to the Cypress tests directory
                      cd services/cypress/tests

                      # Install Cypress and dependencies (if not already installed)
                      npm install

                      # Run Cypress tests
                      npx cypress run
  properties:
    ci:
      codebase:
        connectorRef: Wasi_Test
        repoName: Wasi
        build: <+input>
